parameters:
    default_cdn_strategy: "id"
    env(APP_URL): ''
    APP_URL: "%env(string:APP_URL)%"
    env(REDIS_PREFIX): ''

snap:
    html_sanitizer:
        enabled: true
        cache_dir: '%kernel.cache_dir%'
        cache_enabled: true
    number_range:
        increment_storage: "SQL"
        redis_url: false
    cdn:
        url: ''
        strategy: "%env(string:default:default_cdn_strategy:SNAP_CDN_STRATEGY_DEFAULT)%"
    cache:
        redis_prefix: '%env(REDIS_PREFIX)%'
        tagging:
            each_snippet: true
            each_config: true
        invalidation:
            delay: 0
            delay_options:
                storage: cache
    http_cache:
        reverse_proxy:
            enabled: false
            ban_method: "BAN" # This can defer from used reverse proxy
            hosts: [ "http://varnish" ]
            max_parallel_invalidations: 2
            redis_url: "redis://redis"
            purge_all:
            fastly:

        ignored_url_parameters:
            - 'pk_campaign' # Piwik
            - 'piwik_campaign'
            - 'pk_kwd'
            - 'piwik_kwd'
            - 'pk_keyword'
            - 'mtm_campaign' # Matomo
            - 'matomo_campaign'
            - 'mtm_cid'
            - 'matomo_cid'
            - 'mtm_kwd'
            - 'matomo_kwd'
            - 'mtm_keyword'
            - 'matomo_keyword'
            - 'mtm_source'
            - 'matomo_source'
            - 'mtm_medium'
            - 'matomo_medium'
            - 'mtm_content'
            - 'matomo_content'
            - 'mtm_group'
            - 'matomo_group'
            - 'mtm_placement'
            - 'matomo_placement'
            - 'pixelId' # Yahoo
            - 'kwid'
            - 'kw'
            - 'chl'
            - 'dv'
            - 'nk'
            - 'pa'
            - 'camid'
            - 'adgid'
            - 'utm_term' # Google
            - 'utm_source'
            - 'utm_medium'
            - 'utm_campaign'
            - 'utm_content'
            - 'cx'
            - 'ie'
            - 'cof'
            - 'siteurl'
            - '_ga'
            - 'adgroupid'
            - 'campaignid'
            - 'adid'
            - 'gclsrc' # Google DoubleClick
            - 'gclid'
            - 'fbclid' # Facebook
            - 'fb_action_ids'
            - 'fb_action_types'
            - 'fb_source'
            - 'mc_cid' # Mailchimp
            - 'mc_eid'
            - '_bta_tid' # Bronto
            - '_bta_c'
            - 'trk_contact' # Listrak
            - 'trk_msg'
            - 'trk_module'
            - 'trk_sid'
            - 'gdfms'  # GodataFeed
            - 'gdftrk'
            - 'gdffi'
            - '_ke'  # Klaviyo
            - 'redirect_log_mongo_id' # Klaviyo
            - 'redirect_mongo_id'
            - 'sb_referer_host'
            - 'mkwid' # Marin
            - 'pcrid'
            - 'ef_id' # Adobe Advertising Cloud
            - 's_kwcid' # Adobe Analytics
            - 'msclkid' # Microsoft Advertising
            - 'dm_i' # dotdigital
            - 'epik' # Pinterest
            - 'pp'
    profiler:
        integrations: []
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"
        temp:
            type: "local"
            config:
                root: "%kernel.project_dir%/var"
        asset:
        allowed_extensions: ["jpg", "jpeg", "png", "webp", "avif", "gif", "svg", "bmp", "tiff", "tif", "eps", "webm", "mkv", "flv", "ogv", "ogg", "mov", "mp4", "avi", "wmv", "pdf", "aac", "mp3", "wav", "flac", "oga", "wma", "txt", "doc", "ico", "glb"]
        private_allowed_extensions: ["jpg", "jpeg", "png", "webp", "avif", "gif", "svg", "bmp", "tiff", "tif", "eps", "webm", "mkv", "flv", "ogv", "ogg", "mov", "mp4", "avi", "wmv", "pdf", "aac", "mp3", "wav", "flac", "oga", "wma", "txt", "doc", "ico", "glb", "zip", "rar"]
        private_local_download_strategy: "php"

    increment:
        user_activity:
            type: 'mysql'

            # type: 'array'

            # type: 'redis'
            #     config:
            #         url: 'redis://localhost'

        message_queue:
            type: 'mysql'

            # type: 'array'

            # type: 'redis'
            #     config:
            #         url: 'redis://localhost'

    api:
        max_limit: 500
        api_browser:
            auth_required: true
        store:
            context_lifetime: 'P1D' # 1 day interval, see also https://www.php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
            max_limit: 100
        jwt_key:
            private_key_path: 'file://%kernel.project_dir%/config/jwt/private.pem'
            private_key_passphrase: 'snap'
            public_key_path: 'file://%kernel.project_dir%/config/jwt/public.pem'
        rate_limiter:
            login:
                enabled: true
                policy: 'time_backoff'
                reset: '24 hours' # reset limit after this time if no more requests failed
                limits:
                    - limit: 10
                      interval: '10 seconds'
                    - limit: 15
                      interval: '30 seconds'
                    - limit: 20
                      interval: '60 seconds'
            oauth:
                enabled: true
                policy: 'time_backoff'
                reset: '24 hours'
                limits:
                    - limit: 10
                      interval: '10 seconds'
                    - limit: 15
                      interval: '30 seconds'
                    - limit: 20
                      interval: '60 seconds'
            reset_password:
                enabled: true
                policy: 'time_backoff'
                reset: '24 hours'
                limits:
                    - limit: 3
                      interval: '30 seconds'
                    - limit: 5
                      interval: '60 seconds'
                    - limit: 10
                      interval: '90 seconds'
            user_recovery:
                enabled: true
                policy: 'time_backoff'
                reset: '24 hours'
                limits:
                    - limit: 3
                      interval: '30 seconds'
                    - limit: 5
                      interval: '60 seconds'
                    - limit: 10
                      interval: '90 seconds'
            notification:
                enabled: true
                policy: 'time_backoff'
                reset: '24 hours'
                limits:
                    - limit: 10
                      interval: '10 seconds'
                    - limit: 15
                      interval: '30 seconds'
                    - limit: 20
                      interval: '60 seconds'

    admin_worker:
        enable_admin_worker: true
        enable_queue_stats_worker: true
        enable_notification_worker: true
        # This has to be lower than PHP's max_execution_time (default: 30s)
        poll_interval: 20
        transports: ["async", "low_priority"]

    auto_update:
        enabled: true

    store:
        frw: false

    deployment:
        blue_green: '%env(bool:default:defaults_bool_true:BLUE_GREEN_DEPLOYMENT)%'
        cluster_setup: false

    media:
        enable_url_upload_feature: true
        enable_url_validation: true
        url_upload_max_size: 0

    dal:
        batch_size: 125
        max_rule_prices: 100
        versioning:
            expire_days: 30

    mail:
        update_mail_variables_on_send: true

    logger:
        file_rotation_count: 14
        exclude_exception:
            - League\OAuth2\Server\Exception\OAuthServerException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - SnapAdmin\Core\Framework\Routing\Exception\LanguageNotFoundException
        exclude_events:
            - user.recovery.request
            - customer.recovery.request
        error_code_log_levels:
            CONTENT__MEDIA_INVALID_CONTENT_LENGTH: notice
            CONTENT__MEDIA_INVALID_URL: notice
            CONTENT__MEDIA_ILLEGAL_URL: notice
            CONTENT__MEDIA_DISABLE_URL_UPLOAD_FEATURE: notice
            CONTENT__MEDIA_CANNOT_OPEN_SOURCE_STREAM_TO_READ: notice
            CONTENT__MEDIA_CANNOT_OPEN_SOURCE_STREAM_TO_WRITE: notice
            CONTENT__MEDIA_FILE_SIZE_LIMIT_EXCEEDED: notice
            CONTENT__MEDIA_MISSING_FILE_EXTENSION: notice
            CONTENT__MEDIA_ILLEGAL_FILE_NAME: notice
            CONTENT__MEDIA_EMPTY_FILE: notice
            CONTENT__MEDIA_INVALID_FILE: notice
            CONTENT__MEDIA_EMPTY_FILE_NAME: notice
            CONTENT__MEDIA_FOLDER_NOT_FOUND: notice
            CONTENT__MEDIA_FOLDER_NAME_NOT_FOUND: notice
            CONTENT__MEDIA_FILE_TYPE_NOT_SUPPORTED: notice
            CONTENT__MEDIA_EMPTY_ID: notice
            CONTENT__MEDIA_FILE_NOT_SUPPORTED_FOR_THUMBNAIL: notice
            CONTENT__MEDIA_STRATEGY_NOT_FOUND: notice
            CONTENT__MEDIA_DUPLICATED_FILE_NAME: notice
            CONTENT__MEDIA_NOT_FOUND: notice
            CONTENT__MEDIA_MISSING_FILE: notice
            FRAMEWORK__RATE_LIMIT_EXCEEDED: notice
            FRAMEWORK__CANNOT_CREATE_NEW_VERSION: notice
            FRAMEWORK__SALES_CHANNEL_ID_PARAMETER_IS_MISSING: notice
            FRAMEWORK__TEMPLATE_PARAMETER_IS_MISSING: notice
            FRAMEWORK__ROUTE_NAME_PARAMETER_IS_MISSING: notice
            FRAMEWORK__ENTITY_NAME_PARAMETER_IS_MISSING: notice
            FRAMEWORK__SALES_CHANNEL_NOT_FOUND: notice
            FRAMEWORK__API_UNSUPPORTED_ASSOCIATION_FIELD_EXCEPTION: notice
            FRAMEWORK__NOT_EXISTING_RELATION_EXCEPTION: notice
            FRAMEWORK__INVALID_VERSION_ID: notice
            FRAMEWORK__API_TYPE_PARAMETER_INVALID: notice
            FRAMEWORK__APP_ID_PARAMETER_IS_MISSING: notice
            FRAMEWORK__APP_NOT_COMPATIBLE: notice
            FRAMEWORK__API_SALES_CHANNEL_ID_PARAMETER_IS_MISSING: notice
            FRAMEWORK__API_CUSTOMER_ID_PARAMETER_IS_MISSING: notice
            FRAMEWORK__API_INVALID_ACCESS_KEY: notice
            FRAMEWORK__API_INVALID_ACCESS_KEY_IDENTIFIER: notice
            FRAMEWORK__API_SHIPPING_COSTS_PARAMETER_IS_MISSING: notice
            FRAMEWORK__KEY_PARAMETER_IS_MISSING: notice
            FRAMEWORK__CLUSTER_PARAMETER_IS_MISSING: notice
            FRAMEWORK__INVALID_API_CRITERIA_IDS: notice
            FRAMEWORK__INVALID_CRITERIA_IDS: notice
            FRAMEWORK__DEFINITION_NOT_FOUND: notice
            FRAMEWORK__LANGUAGE_NOT_FOUND: notice
            FRAMEWORK__SYNC_ACTION_PROCESS_INTERRUPTED: notice
            FRAMEWORK__WRITE_TYPE_INTEND_ERROR: notice
            SYSTEM__NO_CONTEXT_DATA_EXCEPTION: notice
            SYSTEM__SCOPE_NOT_FOUND: notice
            FRAMEWORK__EXTENSION_THEME_STILL_IN_USE: notice
            FRAMEWORK__INVALID_TEMPLATE_SYNTAX: notice

    twig:
        allowed_php_functions: []

    dompdf:
        options:
            isRemoteEnabled: true
