name: Unit

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  php:
    name: "PHPUnit with PHP ${{ matrix.php-version }}"
    continue-on-error: ${{ !matrix.stable }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.2
            stable: true
          - php-version: 8.3
            stable: false
          - php-version: 8.4
            stable: false
    env:
      TEST_SUITES: 'administration system framework profiling migration'
      APP_ENV: test
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/root
      APP_URL: http://localhost:8000
      APP_SECRET: devsecret
      BLUE_GREEN_DEPLOYMENT: 1
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
        ports:
          - "3306:3306"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache Composer Archives
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Configure for Unstable
        run: |
          composer config platform.php 8.2.99
          composer config -d vendor-bin/cs-fixer platform.php 8.2.99
          composer config -d vendor-bin/rector platform.php 8.2.99
        if: matrix.stable == false
      - name: Setup Composer
        run: |
          composer install -o
